### ISSUE TITLE
Storage of ARLEM zip files

### ISSUE THREAD

**Issue by fwild** [ARETEedu/moodle-ARLEM_repository#1]
Implement the upload (via http, unless we run into trouble with large files and http as upload protocol?) of the ARLEM zip files generated by Mirage·XR.

On the server side: store the zip file somewhere appropriate - not sure whether this is to be best into a mysql table (I think this is a 'blob' storage type, but you better check for performance issues) or whether that is into a server local temp folder.

**Comment by aradjafari** [comment]
This task is done in a sample unity project and need only be integrated to MirageXR.
This issue will be closed after integration

**Comment by jafarigit** [comment]
Now files can be uploaded from Mirage and saved on Moodle using file API
