### ISSUE TITLE
Edit zip - to download, upload, and replace files inside

### ISSUE THREAD

**Issue by fwild** [ARETEedu/moodle-ARLEM_repository#10]
Allow to download and reupload, e.g., an mp3 file inside of the zip. This should be allowed for any files...

**Comment by fwild** [comment]
For owner and admin

**Comment by jafarigit** [comment]
The edit mode is added. In a new page the ARLEM will be displayed with its structure. It is possible to upload the edited files and these changes will be applied on the original zip file.
