### ISSUE TITLE
Change the database update using Task API

### ISSUE THREAD

**Issue by aradjafari** [ARETEedu/moodle-ARLEM_repository#6]
At the moment the arlem list database will be updated in mod_arete_update_arlems_list.php and be called in mod_form.php. Maybe we do this using Task API for a better performance.

**Comment by aradjafari** [comment]
We don't need to update arlems list since we get the files from the Moodle file table.

**Comment by fwild** [comment]
Is this also about storing the additional meta-data (using the spooler later) like "name" and "description" and "language"?
